from antlr4 import FileStream, CommonTokenStream, ParseTreeWalker
from .PgenParser import PgenParser
from .PgenLexer import PgenLexer
from .listener import CustomListener
import argparse


def main(input_file, output_file):
    input_stream = FileStream(input_file)

    lexer = PgenLexer(input_stream)
    token_stream = CommonTokenStream(lexer)

    parser = PgenParser(token_stream)
    tree = parser.start()

    listener = CustomListener(token_stream, output_file)
    walker = ParseTreeWalker()
    walker.walk(listener, tree)


def cli():
    parser = argparse.ArgumentParser(
        description="Autogenerate a fuzzer from an PG file."
    )
    parser.add_argument("input_file", help="Path to the input .pg file")
    parser.add_argument(
        "-o",
        "--out",
        required=False,
        default="output.py",
        help="Path to the output autogenerated Python file",
    )
    args = parser.parse_args()

    input_file = args.input_file
    output_file = args.out

    # Check if the input file exists
    try:
        with open(input_file, "r") as f:
            pass
    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
        exit(1)

    # Check if the output file is .py
    if not output_file.endswith(".py"):
        print("Warning: Output file should have a .py extension.")

    main(input_file, output_file)


if __name__ == "__main__":
    cli()
